import * as express from "express";
const router = express.Router();
import controller from "../../controller/customer_controller";
router.post("/getCustomerTableList", controller.getCustomerTableList);
router.post("/getCustomerTableById", controller.getCustomerTableById);
router.post("/createCustomerTable", controller.createCustomerTable);
router.post("/editCustomerTable", controller.editCustomerTable);
router.post("/deleteCustomerTable", controller.deleteCustomerTable);
router.post("/getCustomerDropdown", controller.getCustomerDropdown);
export default router;
